/*==============================================================*/
/* HISTORICO DE COSTOS COBRADOS POR LA INSTITUCION              */
/*==============================================================*/
SELECT
EXTRACT(year from FACTURA.FECHAFACTURA) AS FECHA,
TIPOSERVICIO.NOMBRETIPOSERVICIO AS SERVICIO,
SUM(TIPOSERVICIO.COSTOSERVICIO) AS DINERO_COBRADO
FROM FACTURA
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE 
INNER JOIN PLANCONTRATADO ON PLANCONTRATADO.IDPLANCONTRATADO = CLIENTE.IDPLANCONTRATADO
INNER JOIN SERVICIO ON SERVICIO.IDPLANCONTRATADO = PLANCONTRATADO.IDPLANCONTRATADO
INNER JOIN TIPOSERVICIO ON TIPOSERVICIO.IDTIPOSERVICIO = SERVICIO.IDTIPOSERVICIO
GROUP BY EXTRACT(year from FACTURA.FECHAFACTURA), TIPOSERVICIO.NOMBRETIPOSERVICIO
ORDER BY EXTRACT(year from FACTURA.FECHAFACTURA)

/*==============================================================*/
/* HISTORICO DE ATENCIONES POR PERSONAL DE TRATAMIENTO          */
/*==============================================================*/
SELECT
EXTRACT(year from FACTURA.FECHAFACTURA) AS FECHA,
CONCAT(PUBLIC.PERSONAL.NOMBRESPERSONAL,' ',PUBLIC.PERSONAL.APELLIDOSPERSONAL) AS NOMBRE_PERSONAL,
COUNT(FACTURA.FECHAFACTURA) AS NUMERO_TRATAMIENTOS
FROM FACTURA
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE 
INNER JOIN PLANCONTRATADO ON PLANCONTRATADO.IDPLANCONTRATADO = CLIENTE.IDPLANCONTRATADO
INNER JOIN SERVICIO ON SERVICIO.IDPLANCONTRATADO = PLANCONTRATADO.IDPLANCONTRATADO
INNER JOIN PERSONAL ON PERSONAL.IDPERSONAL = SERVICIO.IDPERSONAL
INNER JOIN TIPOPERSONAL ON TIPOPERSONAL.IDTIPOPERSONAL = PERSONAL.IDTIPOPERSONAL
WHERE TIPOPERSONAL.NOMBRETIPOPERSONAL LIKE '%Tratamiento%'
GROUP BY EXTRACT(year from FACTURA.FECHAFACTURA), PERSONAL.NOMBRESPERSONAL, PERSONAL.APELLIDOSPERSONAL
ORDER BY EXTRACT(year from FACTURA.FECHAFACTURA)

/*==============================================================*/
/* HISTORICO DE REVISIONES MEDICAS POR DOCTOR                   */
/*==============================================================*/
SELECT
EXTRACT(year from FACTURA.FECHAFACTURA) AS FECHA,
CONCAT(PUBLIC.PERSONAL.NOMBRESPERSONAL,' ',PUBLIC.PERSONAL.APELLIDOSPERSONAL) AS NOMBRE_PERSONAL,
COUNT(CLIENTE.NOMBRESCLIENTE) AS NUMERO_PACIENTES
FROM FACTURA
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE 
INNER JOIN PLANCONTRATADO ON PLANCONTRATADO.IDPLANCONTRATADO = CLIENTE.IDPLANCONTRATADO
INNER JOIN SERVICIO ON SERVICIO.IDPLANCONTRATADO = PLANCONTRATADO.IDPLANCONTRATADO
INNER JOIN PERSONAL ON PERSONAL.IDPERSONAL = SERVICIO.IDPERSONAL
INNER JOIN TIPOPERSONAL ON TIPOPERSONAL.IDTIPOPERSONAL = PERSONAL.IDTIPOPERSONAL
WHERE TIPOPERSONAL.NOMBRETIPOPERSONAL LIKE '%Revisión medica%'
GROUP BY EXTRACT(year from FACTURA.FECHAFACTURA), PERSONAL.NOMBRESPERSONAL, PERSONAL.APELLIDOSPERSONAL
ORDER BY EXTRACT(year from FACTURA.FECHAFACTURA)

/*==============================================================*/
/* HISTORICO DE EVENTOS DE ENTRETENIMIENTO              		*/
/*==============================================================*/
SELECT
EXTRACT(year from FACTURA.FECHAFACTURA) AS FECHA,
SERVICIO.DESCRIPCIONSERVICIO AS SERVICIO,
COUNT(CLIENTE.NOMBRESCLIENTE) AS NUMERO_PACIENTES
FROM FACTURA
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE 
INNER JOIN PLANCONTRATADO ON PLANCONTRATADO.IDPLANCONTRATADO = CLIENTE.IDPLANCONTRATADO
INNER JOIN SERVICIO ON SERVICIO.IDPLANCONTRATADO = PLANCONTRATADO.IDPLANCONTRATADO
INNER JOIN TIPOSERVICIO ON TIPOSERVICIO.IDTIPOSERVICIO = SERVICIO.IDTIPOSERVICIO
WHERE TIPOSERVICIO.NOMBRETIPOSERVICIO LIKE '%Entretenimiento%'
GROUP BY EXTRACT(year from FACTURA.FECHAFACTURA), SERVICIO.DESCRIPCIONSERVICIO
ORDER BY COUNT(CLIENTE.NOMBRESCLIENTE) DESC
LIMIT 1